version: "3"
services:
  chat-db:
    image: postgres:10
    container_name: chat-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      nt-telecom:
  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    expose:
      - "80"
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
      - PGADMIN_CONFIG_LOGIN_BANNER="Authorised users only!"
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
    depends_on:
      - chat-db
    networks:
      nt-telecom:
  spring_boot_app:
    build:
      context: spring
      dockerfile: Dockerfile
    image: spring_boot_image:latest
    container_name: spring-boot-app
    working_dir: /app
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.show-sql=true
      - spring.datasource.url=jdbc:postgresql://chat-db:5432/smartelecomdb
      - spring.datasource.username=${POSTGRES_USER}
      - spring.datasource.password=${POSTGRES_PASSWORD}
      - ruta.imagenes=/app/imagenes
    expose:
      - "8080"
    depends_on:
      - chat-db
    volumes:
      - backend_data:/app
      - ~/int-smarttelecomec/rasa/src/data:/app/data
      - ~/images/:/app/imagenes
    networks:
      nt-telecom:
  rasa:
    build:
      context: rasa
      dockerfile: Dockerfile.engine
    container_name: rasa-server
    image: rasa-engine:latest
    expose:
      - "5005"
    command:
      - run
      - --cors
      - "*"
      - --enable-api
    depends_on:
      - action-server
    networks:
      nt-telecom:
  action-server:
    build:
      context: rasa
      dockerfile: Dockerfile.actions
    container_name: rasa-action-server
    image: rasa-actions:latest
    expose:
      - "5055"
    networks:
      nt-telecom:
  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui:latest
    environment:
      URLS: '[{ url: "https://www.smarttelecomec.com/spring/v3/api-docs", name: "SmartTelecomEc" }]'
    expose:
      - "8080"
    depends_on:
      - spring_boot_app
    networks:
      nt-telecom:
  website:
    build:
      context: website
      dockerfile: Dockerfile
    container_name: website
    image: website:latest
    volumes:
      - ~/images/:/usr/share/nginx/media
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - VIRTUAL_HOST=www.smarttelecomec.com,smarttelecomec.com
      - LETSENCRYPT_HOST=www.smarttelecomec.com,smarttelecomec.com
      - LETSENCRYPT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
    expose:
      - "80"
    depends_on:
      - spring_boot_app
      - rasa
      - pgadmin4
      - swagger-ui
    networks:
      nt-telecom:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    depends_on:
      - website
    networks:
      nt-telecom:
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - TZ=America/Guayaquil
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      nt-telecom:
volumes:
  postgres-data:
    name: telecom-data-odoo-web
  backend_data:
    name: telecom-backend_data
  datos-compartidos:
    name: telecom-datos-compartidos
  certs:
    name: telecom-certs
  html:
    name: telecom-html
  vhostd:
    name: telecom-vhostd
networks:
  nt-telecom:
    name: nt-telecom
    external: true
