# Extend the official Rasa SDK image
FROM rasa/rasa-sdk

WORKDIR /app
COPY  src /app/

# Change back to root user to install dependencies
USER root

# To install system dependencies
RUN apt-get update -qq && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


# Switch back to non-root to run code
USER 1001

# CMD ["start", "--actions", "actions", "--cors", "*"]

CMD ["start","--actions","actions"]